// This file was generated by protogen. DO NOT EDIT.

package sdm

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	sdm "github.com/strongdm/terraform-provider-sdm/sdm/internal/sdk"
)

func dataSourceAccountAttachment() *schema.Resource {
	return &schema.Resource{
		ReadContext: wrapCrudOperation(dataSourceAccountAttachmentList),
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Computed: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
			},

			"account_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The id of the account of this AccountAttachment.",
			},
			"id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Unique identifier of the AccountAttachment.",
			},
			"role_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The id of the attached role of this AccountAttachment.",
			},
			"account_attachments": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{

						"account_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The id of the account of this AccountAttachment.",
						},
						"id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Unique identifier of the AccountAttachment.",
						},
						"role_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The id of the attached role of this AccountAttachment.",
						},
					},
				},
			},
		},
		Timeouts: &schema.ResourceTimeout{
			Default: schema.DefaultTimeout(60 * time.Second),
		},
	}
}

func convertAccountAttachmentFilterFromResourceData(d *schema.ResourceData) (string, []interface{}) {
	filter := ""
	args := []interface{}{}
	if v, ok := d.GetOkExists("account_id"); ok {
		filter += "accountid:? "
		args = append(args, v)
	}
	if v, ok := d.GetOkExists("id"); ok {
		filter += "id:? "
		args = append(args, v)
	}
	if v, ok := d.GetOkExists("role_id"); ok {
		filter += "roleid:? "
		args = append(args, v)
	}
	return filter, args
}

func dataSourceAccountAttachmentList(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	filter, args := convertAccountAttachmentFilterFromResourceData(d)
	resp, err := cc.AccountAttachments().List(ctx, filter, args...)
	if err != nil {
		return fmt.Errorf("cannot list AccountAttachments %s: %w", d.Id(), err)
	}
	ids := []string{}
	type entity = map[string]interface{}
	output := make([]entity, 0)
	for resp.Next() {
		v := resp.Value()
		ids = append(ids, v.ID)
		output = append(output,
			entity{
				"account_id": (v.AccountID),
				"id":         (v.ID),
				"role_id":    (v.RoleID),
			})
	}
	if resp.Err() != nil {
		return fmt.Errorf("failure during list: %w", resp.Err())
	}

	err = d.Set("ids", ids)
	if err != nil {
		return fmt.Errorf("cannot set ids: %w", err)
	}
	err = d.Set("account_attachments", output)
	if err != nil {
		return fmt.Errorf("cannot set output: %w", err)
	}
	d.SetId("AccountAttachment" + filter + fmt.Sprint(args...))
	return nil
}
