// This file was generated by protogen. DO NOT EDIT.

package sdm

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	sdm "github.com/strongdm/terraform-provider-sdm/sdm/internal/sdk"
)

func dataSourceRoleAttachment() *schema.Resource {
	return &schema.Resource{
		ReadContext:        wrapCrudOperation(dataSourceRoleAttachmentList),
		DeprecationMessage: "sdm_role_attachment is deprecated, see docs for more info",
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Computed: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
			},

			"attached_role_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The id of the attached role of this RoleAttachment.",
			},
			"composite_role_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The id of the composite role of this RoleAttachment.",
			},
			"id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Unique identifier of the RoleAttachment.",
			},
			"role_attachments": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{

						"attached_role_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The id of the attached role of this RoleAttachment.",
						},
						"composite_role_id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The id of the composite role of this RoleAttachment.",
						},
						"id": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "Unique identifier of the RoleAttachment.",
						},
					},
				},
			},
		},
		Timeouts: &schema.ResourceTimeout{
			Default: schema.DefaultTimeout(60 * time.Second),
		},
	}
}

func convertRoleAttachmentFilterFromResourceData(d *schema.ResourceData) (string, []interface{}) {
	filter := ""
	args := []interface{}{}
	if v, ok := d.GetOk("attached_role_id"); ok {
		filter += "attachedroleid:? "
		args = append(args, v)
	}
	if v, ok := d.GetOk("composite_role_id"); ok {
		filter += "compositeroleid:? "
		args = append(args, v)
	}
	if v, ok := d.GetOk("id"); ok {
		filter += "id:? "
		args = append(args, v)
	}
	return filter, args
}

func dataSourceRoleAttachmentList(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	filter, args := convertRoleAttachmentFilterFromResourceData(d)
	resp, err := cc.RoleAttachments().List(ctx, filter, args...)
	if err != nil {
		return fmt.Errorf("cannot list RoleAttachments %s: %w", d.Id(), err)
	}
	ids := []string{}
	type entity = map[string]interface{}
	output := make([]entity, 0)
	for resp.Next() {
		v := resp.Value()
		ids = append(ids, v.ID)
		output = append(output,
			entity{
				"attached_role_id":  (v.AttachedRoleID),
				"composite_role_id": (v.CompositeRoleID),
				"id":                (v.ID),
			})
	}
	if resp.Err() != nil {
		return fmt.Errorf("failure during list: %w", resp.Err())
	}

	err = d.Set("ids", ids)
	if err != nil {
		return fmt.Errorf("cannot set ids: %w", err)
	}
	err = d.Set("role_attachments", output)
	if err != nil {
		return fmt.Errorf("cannot set output: %w", err)
	}
	d.SetId("RoleAttachment" + filter + fmt.Sprint(args...))
	return nil
}
