// Code generated by protogen. DO NOT EDIT.

package sdm

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	sdm "github.com/strongdm/terraform-provider-sdm/sdm/internal/sdk"
)

func dataSourceProxyClusterKey() *schema.Resource {
	return &schema.Resource{
		ReadContext: wrapCrudOperation(dataSourceProxyClusterKeyList),
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Computed: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
			},

			"id": {
				Type: schema.TypeString,

				Optional:    true,
				Description: "Unique identifier of the Relay.",
			},
			"proxy_cluster_id": {
				Type: schema.TypeString,

				Optional:    true,
				Description: "The ID of the proxy cluster which this key authenticates to.",
			},
			"proxy_cluster_keys": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{

						"id": {
							Type: schema.TypeString,

							Optional:    true,
							Description: "Unique identifier of the Relay.",
						},
						"proxy_cluster_id": {
							Type: schema.TypeString,

							Optional:    true,
							Description: "The ID of the proxy cluster which this key authenticates to.",
						},
					},
				},
			},
		},
		Timeouts: &schema.ResourceTimeout{
			Default: schema.DefaultTimeout(60 * time.Second),
		},
	}
}

func init() {
	dataSourcesMap["sdm_proxy_cluster_key"] = dataSourceProxyClusterKey
}

func convertProxyClusterKeyFilterToPlumbing(d *schema.ResourceData) (string, []interface{}) {
	filter := ""
	args := []interface{}{}
	if v, ok := d.GetOkExists("id"); ok {
		filter += "id:? "
		args = append(args, v)
	}
	if v, ok := d.GetOkExists("proxy_cluster_id"); ok {
		filter += "proxyclusterid:? "
		args = append(args, v)
	}
	return filter, args
}

func dataSourceProxyClusterKeyList(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	filter, args := convertProxyClusterKeyFilterToPlumbing(d)
	resp, err := cc.ProxyClusterKeys().List(ctx, filter, args...)
	if err != nil {
		return fmt.Errorf("cannot list ProxyClusterKeys %s: %w", d.Id(), err)
	}
	ids := []string{}
	type entity = map[string]interface{}
	output := make([]entity, 0)
	for resp.Next() {
		v := resp.Value()
		ids = append(ids, v.ID)
		output = append(output,
			entity{
				"id":               (v.ID),
				"proxy_cluster_id": (v.ProxyClusterID),
			})
	}
	if resp.Err() != nil {
		return fmt.Errorf("failure during list: %w", resp.Err())
	}

	err = d.Set("ids", ids)
	if err != nil {
		return fmt.Errorf("cannot set ids: %w", err)
	}
	err = d.Set("proxy_cluster_keys", output)
	if err != nil {
		return fmt.Errorf("cannot set output: %w", err)
	}
	d.SetId("ProxyClusterKey" + filter + fmt.Sprint(args...))
	return nil
}
