// Code generated by protogen. DO NOT EDIT.
// See pkg/api/v1/templates/terraform-provider-sdm/sdm/*_test.go.tpl

package sdm

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccSDMControlPanel_SSHCAPublicKeyGet(t *testing.T) {
	initAcceptanceTest(t)

	dataName := randomWithPrefix("test")
	resource.ParallelTest(t, resource.TestCase{
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccSDMControlPanelSSHCAPublicKeyGetConfig(dataName),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("data.sdm_ssh_ca_pubkey."+dataName, "public_key"),
				),
			},
		},
	})
}

func testAccSDMControlPanelSSHCAPublicKeyGetConfig(dataName string) string {
	return fmt.Sprintf(`
	data "sdm_ssh_ca_pubkey" "%s" {
	}`,
		dataName,
	)
}

func TestAccSDMControlPanel_RDPCAPublicKeyGet(t *testing.T) {
	initAcceptanceTest(t)

	dataName := randomWithPrefix("test")
	resource.ParallelTest(t, resource.TestCase{
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccSDMControlPanelRDPCAPublicKeyGetConfig(dataName),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("data.sdm_rdp_ca_pubkey."+dataName, "public_key"),
				),
			},
		},
	})
}

func testAccSDMControlPanelRDPCAPublicKeyGetConfig(dataName string) string {
	return fmt.Sprintf(`
        data "sdm_rdp_ca_pubkey" "%s" {
        }`,
		dataName,
	)
}
