// This file was generated by protogen. DO NOT EDIT.

package sdm

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"

	sdm "github.com/strongdm/strongdm-sdk-go"
)

func resourceSecretStore() *schema.Resource {
	return &schema.Resource{
		Create: wrapCrudOperation(resourceSecretStoreCreate),
		Read:   wrapCrudOperation(resourceSecretStoreRead),
		Update: wrapCrudOperation(resourceSecretStoreUpdate),
		Delete: wrapCrudOperation(resourceSecretStoreDelete),
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"vault_tls": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Unique human-readable name of the SecretStore.",
						},
						"server_address": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "",
						},
						"ca_cert_path": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "",
						},
						"client_cert_path": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "",
						},
						"client_key_path": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "",
						},
						"tags": {
							Type: schema.TypeMap,

							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
							Optional:    true,
							Description: "Tags is a map of key, value pairs.",
						},
					},
				},
			},
			"vault_token": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "Unique human-readable name of the SecretStore.",
						},
						"server_address": {
							Type:        schema.TypeString,
							Required:    true,
							Description: "",
						},
						"tags": {
							Type: schema.TypeMap,

							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
							Optional:    true,
							Description: "Tags is a map of key, value pairs.",
						},
					},
				},
			},
		},
		Timeouts: &schema.ResourceTimeout{
			Default: schema.DefaultTimeout(60 * time.Second),
		},
	}
}
func convertSecretStoreFromResourceData(d *schema.ResourceData) sdm.SecretStore {
	if list := d.Get("vault_tls").([]interface{}); len(list) > 0 {
		raw, ok := list[0].(map[string]interface{})
		if !ok {
			return &sdm.VaultTLSStore{}
		}
		out := &sdm.VaultTLSStore{
			ID:             d.Id(),
			Name:           convertStringFromMap(raw, "name"),
			ServerAddress:  convertStringFromMap(raw, "server_address"),
			CACertPath:     convertStringFromMap(raw, "ca_cert_path"),
			ClientCertPath: convertStringFromMap(raw, "client_cert_path"),
			ClientKeyPath:  convertStringFromMap(raw, "client_key_path"),
			Tags:           convertTagsFromMap(raw, "tags"),
		}
		return out
	}
	if list := d.Get("vault_token").([]interface{}); len(list) > 0 {
		raw, ok := list[0].(map[string]interface{})
		if !ok {
			return &sdm.VaultTokenStore{}
		}
		out := &sdm.VaultTokenStore{
			ID:            d.Id(),
			Name:          convertStringFromMap(raw, "name"),
			ServerAddress: convertStringFromMap(raw, "server_address"),
			Tags:          convertTagsFromMap(raw, "tags"),
		}
		return out
	}
	return nil
}

func resourceSecretStoreCreate(d *schema.ResourceData, cc *sdm.Client) error {
	ctx, cancel := context.WithTimeout(context.Background(), d.Timeout(schema.TimeoutCreate))
	defer cancel()
	localVersion := convertSecretStoreFromResourceData(d)
	resp, err := cc.SecretStores().Create(ctx, localVersion)
	if err != nil {
		return fmt.Errorf("cannot create SecretStore: %w", err)
	}
	d.SetId(resp.SecretStore.GetID())
	switch v := resp.SecretStore.(type) {
	case *sdm.VaultTLSStore:
		localV, _ := localVersion.(*sdm.VaultTLSStore)
		_ = localV
		d.Set("vault_tls", []map[string]interface{}{
			{
				"name":             (v.Name),
				"server_address":   (v.ServerAddress),
				"ca_cert_path":     (v.CACertPath),
				"client_cert_path": (v.ClientCertPath),
				"client_key_path":  (v.ClientKeyPath),
				"tags":             convertTagsToMap(v.Tags),
			},
		})
	case *sdm.VaultTokenStore:
		localV, _ := localVersion.(*sdm.VaultTokenStore)
		_ = localV
		d.Set("vault_token", []map[string]interface{}{
			{
				"name":           (v.Name),
				"server_address": (v.ServerAddress),
				"tags":           convertTagsToMap(v.Tags),
			},
		})
	}
	return nil
}

func resourceSecretStoreRead(d *schema.ResourceData, cc *sdm.Client) error {
	ctx, cancel := context.WithTimeout(context.Background(), d.Timeout(schema.TimeoutRead))
	defer cancel()
	localVersion := convertSecretStoreFromResourceData(d)
	_ = localVersion
	resp, err := cc.SecretStores().Get(ctx, d.Id())
	var errNotFound *sdm.NotFoundError
	if err != nil && errors.As(err, &errNotFound) {
		d.SetId("")
		return nil
	} else if err != nil {
		return fmt.Errorf("cannot read SecretStore %s: %w", d.Id(), err)
	}
	switch v := resp.SecretStore.(type) {
	case *sdm.VaultTLSStore:
		localV, ok := localVersion.(*sdm.VaultTLSStore)
		if !ok {
			localV = &sdm.VaultTLSStore{}
		}
		_ = localV
		d.Set("vault_tls", []map[string]interface{}{
			{
				"name":             (v.Name),
				"server_address":   (v.ServerAddress),
				"ca_cert_path":     (v.CACertPath),
				"client_cert_path": (v.ClientCertPath),
				"client_key_path":  (v.ClientKeyPath),
				"tags":             convertTagsToMap(v.Tags),
			},
		})
	case *sdm.VaultTokenStore:
		localV, ok := localVersion.(*sdm.VaultTokenStore)
		if !ok {
			localV = &sdm.VaultTokenStore{}
		}
		_ = localV
		d.Set("vault_token", []map[string]interface{}{
			{
				"name":           (v.Name),
				"server_address": (v.ServerAddress),
				"tags":           convertTagsToMap(v.Tags),
			},
		})
	}
	return nil
}
func resourceSecretStoreUpdate(d *schema.ResourceData, cc *sdm.Client) error {
	ctx, cancel := context.WithTimeout(context.Background(), d.Timeout(schema.TimeoutUpdate))
	defer cancel()
	resp, err := cc.SecretStores().Update(ctx, convertSecretStoreFromResourceData(d))
	if err != nil {
		return fmt.Errorf("cannot update SecretStore %s: %w", d.Id(), err)
	}
	d.SetId(resp.SecretStore.GetID())
	return resourceSecretStoreRead(d, cc)
}
func resourceSecretStoreDelete(d *schema.ResourceData, cc *sdm.Client) error {
	ctx, cancel := context.WithTimeout(context.Background(), d.Timeout(schema.TimeoutDelete))
	defer cancel()
	var errNotFound *sdm.NotFoundError
	_, err := cc.SecretStores().Delete(ctx, d.Id())
	if err != nil && errors.As(err, &errNotFound) {
		return nil
	}
	return err
}
