// This file was generated by protogen. DO NOT EDIT.

package sdm

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	sdm "github.com/strongdm/terraform-provider-sdm/sdm/internal/sdk"
)

func resourceRole() *schema.Resource {
	return &schema.Resource{
		CreateContext: wrapCrudOperation(resourceRoleCreate),
		ReadContext:   wrapCrudOperation(resourceRoleRead),
		UpdateContext: wrapCrudOperation(resourceRoleUpdate),
		DeleteContext: wrapCrudOperation(resourceRoleDelete),
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"composite": {
				Type:        schema.TypeBool,
				Optional:    true,
				ForceNew:    true,
				Description: "Composite is true if the Role is a composite role.  Deprecated: composite roles are deprecated, use multi-role instead.",
				Deprecated:  "composite is deprecated, see docs for more info",
			},
			"name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Unique human-readable name of the Role.",
			},
			"tags": {
				Type:        schema.TypeMap,
				Elem:        tagsElemType,
				Optional:    true,
				Description: "Tags is a map of key, value pairs.",
			},
			"access_rule": accessRuleSchema,
		},
		Timeouts: &schema.ResourceTimeout{
			Default: schema.DefaultTimeout(60 * time.Second),
		},
	}
}
func convertRoleFromResourceData(d *schema.ResourceData) *sdm.Role {
	return &sdm.Role{
		ID:          d.Id(),
		Composite:   convertBoolFromResourceData(d, "composite"),
		Name:        convertStringFromResourceData(d, "name"),
		Tags:        convertTagsFromResourceData(d, "tags"),
		AccessRules: convertAccessRulesFromResourceData(d, "access_rule"),
	}
}

func resourceRoleCreate(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	localVersion := convertRoleFromResourceData(d)

	resp, err := cc.Roles().Create(ctx, localVersion)
	if err != nil {
		return fmt.Errorf("cannot create Role: %w", err)
	}
	d.SetId(resp.Role.ID)
	v := resp.Role
	d.Set("composite", (v.Composite))
	d.Set("name", (v.Name))
	d.Set("tags", convertTagsToMap(v.Tags))
	d.Set("access_rule", convertAccessRulesToMap(v.AccessRules))
	return nil
}

func resourceRoleRead(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	localVersion := convertRoleFromResourceData(d)
	_ = localVersion

	resp, err := cc.Roles().Get(ctx, d.Id())
	var errNotFound *sdm.NotFoundError
	if err != nil && errors.As(err, &errNotFound) {
		d.SetId("")
		return nil
	} else if err != nil {
		return fmt.Errorf("cannot read Role %s: %w", d.Id(), err)
	}
	v := resp.Role
	d.Set("composite", (v.Composite))
	d.Set("name", (v.Name))
	d.Set("tags", convertTagsToMap(v.Tags))
	d.Set("access_rule", convertAccessRulesToMap(v.AccessRules))
	return nil
}
func resourceRoleUpdate(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {

	resp, err := cc.Roles().Update(ctx, convertRoleFromResourceData(d))
	if err != nil {
		return fmt.Errorf("cannot update Role %s: %w", d.Id(), err)
	}
	d.SetId(resp.Role.ID)
	return resourceRoleRead(ctx, d, cc)
}
func resourceRoleDelete(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	var errNotFound *sdm.NotFoundError
	_, err := cc.Roles().Delete(ctx, d.Id())
	if err != nil && errors.As(err, &errNotFound) {
		return nil
	}
	return err
}
