// Code generated by protogen. DO NOT EDIT.

package sdm

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	sdm "github.com/strongdm/terraform-provider-sdm/sdm/internal/sdk"
)

func resourcePeeringGroup() *schema.Resource {
	return &schema.Resource{
		CreateContext: wrapCrudOperation(resourcePeeringGroupCreate),
		ReadContext:   wrapCrudOperation(resourcePeeringGroupRead),
		DeleteContext: wrapCrudOperation(resourcePeeringGroupDelete),
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"name": {
				Type: schema.TypeString,

				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				Description: "Unique human-readable name of the PeeringGroup.",
			},
		},
		Timeouts: &schema.ResourceTimeout{
			Default: schema.DefaultTimeout(60 * time.Second),
			Create:  schema.DefaultTimeout(60 * time.Second),
			Read:    schema.DefaultTimeout(60 * time.Second),
			Delete:  schema.DefaultTimeout(60 * time.Second),
		},
	}
}

func init() {
	resourcesMap["sdm_peering_group"] = resourcePeeringGroup
}
func convertPeeringGroupToPlumbing(d *schema.ResourceData) *sdm.PeeringGroup {
	return &sdm.PeeringGroup{
		ID:   d.Id(),
		Name: convertStringToPlumbing(d.Get("name")),
	}
}

func resourcePeeringGroupCreate(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	ctx, cancel := context.WithTimeout(ctx, d.Timeout(schema.TimeoutCreate))
	defer cancel()
	localVersion := convertPeeringGroupToPlumbing(d)
	resp, err := cc.PeeringGroups().Create(ctx, localVersion)
	if err != nil {
		return fmt.Errorf("cannot create PeeringGroup: %w", err)
	}
	d.SetId(resp.PeeringGroup.ID)
	v := resp.PeeringGroup
	d.Set("name", (v.Name))
	return nil
}

func resourcePeeringGroupRead(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	ctx, cancel := context.WithTimeout(ctx, d.Timeout(schema.TimeoutRead))
	defer cancel()
	localVersion := convertPeeringGroupToPlumbing(d)
	_ = localVersion
	resp, err := cc.PeeringGroups().Get(ctx, d.Id())
	var errNotFound *sdm.NotFoundError
	if err != nil && errors.As(err, &errNotFound) {
		d.SetId("")
		return nil
	} else if err != nil {
		return fmt.Errorf("cannot read PeeringGroup %s: %w", d.Id(), err)
	}
	v := resp.PeeringGroup
	d.Set("name", (v.Name))
	return nil
}
func resourcePeeringGroupDelete(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	ctx, cancel := context.WithTimeout(ctx, d.Timeout(schema.TimeoutDelete))
	defer cancel()
	var errNotFound *sdm.NotFoundError
	_, err := cc.PeeringGroups().Delete(ctx, d.Id())
	if err != nil && errors.As(err, &errNotFound) {
		return nil
	}
	return err
}
