// Code generated by protogen. DO NOT EDIT.

package sdm

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	sdm "github.com/strongdm/terraform-provider-sdm/sdm/internal/sdk"
)

func resourceWorkflowApprover() *schema.Resource {
	return &schema.Resource{
		CreateContext: wrapCrudOperation(resourceWorkflowApproverCreate),
		ReadContext:   wrapCrudOperation(resourceWorkflowApproverRead),
		DeleteContext: wrapCrudOperation(resourceWorkflowApproverDelete),
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{
			"approver_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The approver id.",
			},
			"workflow_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The workflow id.",
			},
		},
		Timeouts: &schema.ResourceTimeout{
			Default: schema.DefaultTimeout(60 * time.Second),
		},
	}
}
func convertWorkflowApproverToPlumbing(d *schema.ResourceData) *sdm.WorkflowApprover {
	return &sdm.WorkflowApprover{
		ID:         d.Id(),
		ApproverID: convertStringToPlumbing(d.Get("approver_id")),
		WorkflowID: convertStringToPlumbing(d.Get("workflow_id")),
	}
}

func resourceWorkflowApproverCreate(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	localVersion := convertWorkflowApproverToPlumbing(d)
	resp, err := cc.WorkflowApprovers().Create(ctx, localVersion)
	if err != nil {
		return fmt.Errorf("cannot create WorkflowApprover: %w", err)
	}
	d.SetId(resp.WorkflowApprover.ID)
	v := resp.WorkflowApprover
	d.Set("approver_id", (v.ApproverID))
	d.Set("workflow_id", (v.WorkflowID))
	return nil
}

func resourceWorkflowApproverRead(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	localVersion := convertWorkflowApproverToPlumbing(d)
	_ = localVersion
	resp, err := cc.WorkflowApprovers().Get(ctx, d.Id())
	var errNotFound *sdm.NotFoundError
	if err != nil && errors.As(err, &errNotFound) {
		d.SetId("")
		return nil
	} else if err != nil {
		return fmt.Errorf("cannot read WorkflowApprover %s: %w", d.Id(), err)
	}
	v := resp.WorkflowApprover
	d.Set("approver_id", (v.ApproverID))
	d.Set("workflow_id", (v.WorkflowID))
	return nil
}
func resourceWorkflowApproverDelete(ctx context.Context, d *schema.ResourceData, cc *sdm.Client) error {
	var errNotFound *sdm.NotFoundError
	_, err := cc.WorkflowApprovers().Delete(ctx, d.Id())
	if err != nil && errors.As(err, &errNotFound) {
		return nil
	}
	return err
}
