// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AccessRequestsHistoryClient is the client API for AccessRequestsHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessRequestsHistoryClient interface {
	// List gets a list of AccessRequestHistory records matching a given set of criteria.
	List(ctx context.Context, in *AccessRequestHistoryListRequest, opts ...grpc.CallOption) (*AccessRequestHistoryListResponse, error)
}

type accessRequestsHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessRequestsHistoryClient(cc grpc.ClientConnInterface) AccessRequestsHistoryClient {
	return &accessRequestsHistoryClient{cc}
}

func (c *accessRequestsHistoryClient) List(ctx context.Context, in *AccessRequestHistoryListRequest, opts ...grpc.CallOption) (*AccessRequestHistoryListResponse, error) {
	out := new(AccessRequestHistoryListResponse)
	err := c.cc.Invoke(ctx, "/v1.AccessRequestsHistory/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessRequestsHistoryServer is the server API for AccessRequestsHistory service.
// All implementations must embed UnimplementedAccessRequestsHistoryServer
// for forward compatibility
type AccessRequestsHistoryServer interface {
	// List gets a list of AccessRequestHistory records matching a given set of criteria.
	List(context.Context, *AccessRequestHistoryListRequest) (*AccessRequestHistoryListResponse, error)
	mustEmbedUnimplementedAccessRequestsHistoryServer()
}

// UnimplementedAccessRequestsHistoryServer must be embedded to have forward compatible implementations.
type UnimplementedAccessRequestsHistoryServer struct {
}

func (UnimplementedAccessRequestsHistoryServer) List(context.Context, *AccessRequestHistoryListRequest) (*AccessRequestHistoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAccessRequestsHistoryServer) mustEmbedUnimplementedAccessRequestsHistoryServer() {}

// UnsafeAccessRequestsHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessRequestsHistoryServer will
// result in compilation errors.
type UnsafeAccessRequestsHistoryServer interface {
	mustEmbedUnimplementedAccessRequestsHistoryServer()
}

func RegisterAccessRequestsHistoryServer(s grpc.ServiceRegistrar, srv AccessRequestsHistoryServer) {
	s.RegisterService(&_AccessRequestsHistory_serviceDesc, srv)
}

func _AccessRequestsHistory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequestHistoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessRequestsHistoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AccessRequestsHistory/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessRequestsHistoryServer).List(ctx, req.(*AccessRequestHistoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessRequestsHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AccessRequestsHistory",
	HandlerType: (*AccessRequestsHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccessRequestsHistory_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access_requests_history.proto",
}
