// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AccountAttachmentsHistoryClient is the client API for AccountAttachmentsHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountAttachmentsHistoryClient interface {
	// List gets a list of AccountAttachmentHistory records matching a given set of criteria.
	List(ctx context.Context, in *AccountAttachmentHistoryListRequest, opts ...grpc.CallOption) (*AccountAttachmentHistoryListResponse, error)
}

type accountAttachmentsHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountAttachmentsHistoryClient(cc grpc.ClientConnInterface) AccountAttachmentsHistoryClient {
	return &accountAttachmentsHistoryClient{cc}
}

func (c *accountAttachmentsHistoryClient) List(ctx context.Context, in *AccountAttachmentHistoryListRequest, opts ...grpc.CallOption) (*AccountAttachmentHistoryListResponse, error) {
	out := new(AccountAttachmentHistoryListResponse)
	err := c.cc.Invoke(ctx, "/v1.AccountAttachmentsHistory/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountAttachmentsHistoryServer is the server API for AccountAttachmentsHistory service.
// All implementations must embed UnimplementedAccountAttachmentsHistoryServer
// for forward compatibility
type AccountAttachmentsHistoryServer interface {
	// List gets a list of AccountAttachmentHistory records matching a given set of criteria.
	List(context.Context, *AccountAttachmentHistoryListRequest) (*AccountAttachmentHistoryListResponse, error)
	mustEmbedUnimplementedAccountAttachmentsHistoryServer()
}

// UnimplementedAccountAttachmentsHistoryServer must be embedded to have forward compatible implementations.
type UnimplementedAccountAttachmentsHistoryServer struct {
}

func (UnimplementedAccountAttachmentsHistoryServer) List(context.Context, *AccountAttachmentHistoryListRequest) (*AccountAttachmentHistoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAccountAttachmentsHistoryServer) mustEmbedUnimplementedAccountAttachmentsHistoryServer() {
}

// UnsafeAccountAttachmentsHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountAttachmentsHistoryServer will
// result in compilation errors.
type UnsafeAccountAttachmentsHistoryServer interface {
	mustEmbedUnimplementedAccountAttachmentsHistoryServer()
}

func RegisterAccountAttachmentsHistoryServer(s grpc.ServiceRegistrar, srv AccountAttachmentsHistoryServer) {
	s.RegisterService(&_AccountAttachmentsHistory_serviceDesc, srv)
}

func _AccountAttachmentsHistory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountAttachmentHistoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAttachmentsHistoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AccountAttachmentsHistory/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAttachmentsHistoryServer).List(ctx, req.(*AccountAttachmentHistoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountAttachmentsHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AccountAttachmentsHistory",
	HandlerType: (*AccountAttachmentsHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccountAttachmentsHistory_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account_attachments_history.proto",
}
