// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AccountsGroupsHistoryClient is the client API for AccountsGroupsHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountsGroupsHistoryClient interface {
	// List gets a list of AccountGroupHistory records matching a given set of criteria.
	List(ctx context.Context, in *AccountGroupHistoryListRequest, opts ...grpc.CallOption) (*AccountGroupHistoryListResponse, error)
}

type accountsGroupsHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsGroupsHistoryClient(cc grpc.ClientConnInterface) AccountsGroupsHistoryClient {
	return &accountsGroupsHistoryClient{cc}
}

func (c *accountsGroupsHistoryClient) List(ctx context.Context, in *AccountGroupHistoryListRequest, opts ...grpc.CallOption) (*AccountGroupHistoryListResponse, error) {
	out := new(AccountGroupHistoryListResponse)
	err := c.cc.Invoke(ctx, "/v1.AccountsGroupsHistory/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsGroupsHistoryServer is the server API for AccountsGroupsHistory service.
// All implementations must embed UnimplementedAccountsGroupsHistoryServer
// for forward compatibility
type AccountsGroupsHistoryServer interface {
	// List gets a list of AccountGroupHistory records matching a given set of criteria.
	List(context.Context, *AccountGroupHistoryListRequest) (*AccountGroupHistoryListResponse, error)
	mustEmbedUnimplementedAccountsGroupsHistoryServer()
}

// UnimplementedAccountsGroupsHistoryServer must be embedded to have forward compatible implementations.
type UnimplementedAccountsGroupsHistoryServer struct {
}

func (UnimplementedAccountsGroupsHistoryServer) List(context.Context, *AccountGroupHistoryListRequest) (*AccountGroupHistoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAccountsGroupsHistoryServer) mustEmbedUnimplementedAccountsGroupsHistoryServer() {}

// UnsafeAccountsGroupsHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountsGroupsHistoryServer will
// result in compilation errors.
type UnsafeAccountsGroupsHistoryServer interface {
	mustEmbedUnimplementedAccountsGroupsHistoryServer()
}

func RegisterAccountsGroupsHistoryServer(s grpc.ServiceRegistrar, srv AccountsGroupsHistoryServer) {
	s.RegisterService(&_AccountsGroupsHistory_serviceDesc, srv)
}

func _AccountsGroupsHistory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountGroupHistoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsGroupsHistoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AccountsGroupsHistory/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsGroupsHistoryServer).List(ctx, req.(*AccountGroupHistoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountsGroupsHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AccountsGroupsHistory",
	HandlerType: (*AccountsGroupsHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccountsGroupsHistory_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts_groups_history.proto",
}
