// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ActivitiesClient is the client API for Activities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivitiesClient interface {
	// Get reads one Activity by ID.
	Get(ctx context.Context, in *ActivityGetRequest, opts ...grpc.CallOption) (*ActivityGetResponse, error)
	// List gets a list of Activities matching a given set of criteria.
	// The 'before' and 'after' filters can be used to control the time
	// range of the output activities. If not provided, one week of back
	// of activities will be returned.
	List(ctx context.Context, in *ActivityListRequest, opts ...grpc.CallOption) (*ActivityListResponse, error)
}

type activitiesClient struct {
	cc grpc.ClientConnInterface
}

func NewActivitiesClient(cc grpc.ClientConnInterface) ActivitiesClient {
	return &activitiesClient{cc}
}

func (c *activitiesClient) Get(ctx context.Context, in *ActivityGetRequest, opts ...grpc.CallOption) (*ActivityGetResponse, error) {
	out := new(ActivityGetResponse)
	err := c.cc.Invoke(ctx, "/v1.Activities/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesClient) List(ctx context.Context, in *ActivityListRequest, opts ...grpc.CallOption) (*ActivityListResponse, error) {
	out := new(ActivityListResponse)
	err := c.cc.Invoke(ctx, "/v1.Activities/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivitiesServer is the server API for Activities service.
// All implementations must embed UnimplementedActivitiesServer
// for forward compatibility
type ActivitiesServer interface {
	// Get reads one Activity by ID.
	Get(context.Context, *ActivityGetRequest) (*ActivityGetResponse, error)
	// List gets a list of Activities matching a given set of criteria.
	// The 'before' and 'after' filters can be used to control the time
	// range of the output activities. If not provided, one week of back
	// of activities will be returned.
	List(context.Context, *ActivityListRequest) (*ActivityListResponse, error)
	mustEmbedUnimplementedActivitiesServer()
}

// UnimplementedActivitiesServer must be embedded to have forward compatible implementations.
type UnimplementedActivitiesServer struct {
}

func (UnimplementedActivitiesServer) Get(context.Context, *ActivityGetRequest) (*ActivityGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedActivitiesServer) List(context.Context, *ActivityListRequest) (*ActivityListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedActivitiesServer) mustEmbedUnimplementedActivitiesServer() {}

// UnsafeActivitiesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivitiesServer will
// result in compilation errors.
type UnsafeActivitiesServer interface {
	mustEmbedUnimplementedActivitiesServer()
}

func RegisterActivitiesServer(s grpc.ServiceRegistrar, srv ActivitiesServer) {
	s.RegisterService(&_Activities_serviceDesc, srv)
}

func _Activities_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Activities/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).Get(ctx, req.(*ActivityGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activities_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Activities/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServer).List(ctx, req.(*ActivityListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Activities_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Activities",
	HandlerType: (*ActivitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Activities_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Activities_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activities.proto",
}
