// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ApprovalWorkflowStepsHistoryClient is the client API for ApprovalWorkflowStepsHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApprovalWorkflowStepsHistoryClient interface {
	// List gets a list of ApprovalWorkflowStepHistory records matching a given set of criteria.
	List(ctx context.Context, in *ApprovalWorkflowStepHistoryListRequest, opts ...grpc.CallOption) (*ApprovalWorkflowStepHistoryListResponse, error)
}

type approvalWorkflowStepsHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewApprovalWorkflowStepsHistoryClient(cc grpc.ClientConnInterface) ApprovalWorkflowStepsHistoryClient {
	return &approvalWorkflowStepsHistoryClient{cc}
}

func (c *approvalWorkflowStepsHistoryClient) List(ctx context.Context, in *ApprovalWorkflowStepHistoryListRequest, opts ...grpc.CallOption) (*ApprovalWorkflowStepHistoryListResponse, error) {
	out := new(ApprovalWorkflowStepHistoryListResponse)
	err := c.cc.Invoke(ctx, "/v1.ApprovalWorkflowStepsHistory/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApprovalWorkflowStepsHistoryServer is the server API for ApprovalWorkflowStepsHistory service.
// All implementations must embed UnimplementedApprovalWorkflowStepsHistoryServer
// for forward compatibility
type ApprovalWorkflowStepsHistoryServer interface {
	// List gets a list of ApprovalWorkflowStepHistory records matching a given set of criteria.
	List(context.Context, *ApprovalWorkflowStepHistoryListRequest) (*ApprovalWorkflowStepHistoryListResponse, error)
	mustEmbedUnimplementedApprovalWorkflowStepsHistoryServer()
}

// UnimplementedApprovalWorkflowStepsHistoryServer must be embedded to have forward compatible implementations.
type UnimplementedApprovalWorkflowStepsHistoryServer struct {
}

func (UnimplementedApprovalWorkflowStepsHistoryServer) List(context.Context, *ApprovalWorkflowStepHistoryListRequest) (*ApprovalWorkflowStepHistoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedApprovalWorkflowStepsHistoryServer) mustEmbedUnimplementedApprovalWorkflowStepsHistoryServer() {
}

// UnsafeApprovalWorkflowStepsHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApprovalWorkflowStepsHistoryServer will
// result in compilation errors.
type UnsafeApprovalWorkflowStepsHistoryServer interface {
	mustEmbedUnimplementedApprovalWorkflowStepsHistoryServer()
}

func RegisterApprovalWorkflowStepsHistoryServer(s grpc.ServiceRegistrar, srv ApprovalWorkflowStepsHistoryServer) {
	s.RegisterService(&_ApprovalWorkflowStepsHistory_serviceDesc, srv)
}

func _ApprovalWorkflowStepsHistory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalWorkflowStepHistoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalWorkflowStepsHistoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ApprovalWorkflowStepsHistory/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalWorkflowStepsHistoryServer).List(ctx, req.(*ApprovalWorkflowStepHistoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApprovalWorkflowStepsHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ApprovalWorkflowStepsHistory",
	HandlerType: (*ApprovalWorkflowStepsHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ApprovalWorkflowStepsHistory_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "approval_workflow_steps_history.proto",
}
