// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GrantedAccountEntitlementsClient is the client API for GrantedAccountEntitlements service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrantedAccountEntitlementsClient interface {
	// List gets a list of GrantedAccountEntitlement records matching a given set of criteria.
	List(ctx context.Context, in *GrantedAccountEntitlementListRequest, opts ...grpc.CallOption) (*GrantedAccountEntitlementListResponse, error)
}

type grantedAccountEntitlementsClient struct {
	cc grpc.ClientConnInterface
}

func NewGrantedAccountEntitlementsClient(cc grpc.ClientConnInterface) GrantedAccountEntitlementsClient {
	return &grantedAccountEntitlementsClient{cc}
}

func (c *grantedAccountEntitlementsClient) List(ctx context.Context, in *GrantedAccountEntitlementListRequest, opts ...grpc.CallOption) (*GrantedAccountEntitlementListResponse, error) {
	out := new(GrantedAccountEntitlementListResponse)
	err := c.cc.Invoke(ctx, "/v1.GrantedAccountEntitlements/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrantedAccountEntitlementsServer is the server API for GrantedAccountEntitlements service.
// All implementations must embed UnimplementedGrantedAccountEntitlementsServer
// for forward compatibility
type GrantedAccountEntitlementsServer interface {
	// List gets a list of GrantedAccountEntitlement records matching a given set of criteria.
	List(context.Context, *GrantedAccountEntitlementListRequest) (*GrantedAccountEntitlementListResponse, error)
	mustEmbedUnimplementedGrantedAccountEntitlementsServer()
}

// UnimplementedGrantedAccountEntitlementsServer must be embedded to have forward compatible implementations.
type UnimplementedGrantedAccountEntitlementsServer struct {
}

func (UnimplementedGrantedAccountEntitlementsServer) List(context.Context, *GrantedAccountEntitlementListRequest) (*GrantedAccountEntitlementListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedGrantedAccountEntitlementsServer) mustEmbedUnimplementedGrantedAccountEntitlementsServer() {
}

// UnsafeGrantedAccountEntitlementsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrantedAccountEntitlementsServer will
// result in compilation errors.
type UnsafeGrantedAccountEntitlementsServer interface {
	mustEmbedUnimplementedGrantedAccountEntitlementsServer()
}

func RegisterGrantedAccountEntitlementsServer(s grpc.ServiceRegistrar, srv GrantedAccountEntitlementsServer) {
	s.RegisterService(&_GrantedAccountEntitlements_serviceDesc, srv)
}

func _GrantedAccountEntitlements_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantedAccountEntitlementListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantedAccountEntitlementsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GrantedAccountEntitlements/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantedAccountEntitlementsServer).List(ctx, req.(*GrantedAccountEntitlementListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrantedAccountEntitlements_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.GrantedAccountEntitlements",
	HandlerType: (*GrantedAccountEntitlementsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _GrantedAccountEntitlements_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "granted_account_entitlements.proto",
}
