// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GroupsRolesClient is the client API for GroupsRoles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupsRolesClient interface {
	// Create registers a new GroupRole.
	Create(ctx context.Context, in *GroupRoleCreateRequest, opts ...grpc.CallOption) (*GroupRoleCreateResponse, error)
	// Get reads one GroupRole by ID.
	Get(ctx context.Context, in *GroupRoleGetRequest, opts ...grpc.CallOption) (*GroupRoleGetResponse, error)
	// Delete removes a GroupRole by ID.
	Delete(ctx context.Context, in *GroupRoleDeleteRequest, opts ...grpc.CallOption) (*GroupRoleDeleteResponse, error)
	// List gets a list of GroupRoles matching a given set of criteria.
	List(ctx context.Context, in *GroupRoleListRequest, opts ...grpc.CallOption) (*GroupRoleListResponse, error)
}

type groupsRolesClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupsRolesClient(cc grpc.ClientConnInterface) GroupsRolesClient {
	return &groupsRolesClient{cc}
}

func (c *groupsRolesClient) Create(ctx context.Context, in *GroupRoleCreateRequest, opts ...grpc.CallOption) (*GroupRoleCreateResponse, error) {
	out := new(GroupRoleCreateResponse)
	err := c.cc.Invoke(ctx, "/v1.GroupsRoles/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsRolesClient) Get(ctx context.Context, in *GroupRoleGetRequest, opts ...grpc.CallOption) (*GroupRoleGetResponse, error) {
	out := new(GroupRoleGetResponse)
	err := c.cc.Invoke(ctx, "/v1.GroupsRoles/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsRolesClient) Delete(ctx context.Context, in *GroupRoleDeleteRequest, opts ...grpc.CallOption) (*GroupRoleDeleteResponse, error) {
	out := new(GroupRoleDeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.GroupsRoles/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsRolesClient) List(ctx context.Context, in *GroupRoleListRequest, opts ...grpc.CallOption) (*GroupRoleListResponse, error) {
	out := new(GroupRoleListResponse)
	err := c.cc.Invoke(ctx, "/v1.GroupsRoles/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupsRolesServer is the server API for GroupsRoles service.
// All implementations must embed UnimplementedGroupsRolesServer
// for forward compatibility
type GroupsRolesServer interface {
	// Create registers a new GroupRole.
	Create(context.Context, *GroupRoleCreateRequest) (*GroupRoleCreateResponse, error)
	// Get reads one GroupRole by ID.
	Get(context.Context, *GroupRoleGetRequest) (*GroupRoleGetResponse, error)
	// Delete removes a GroupRole by ID.
	Delete(context.Context, *GroupRoleDeleteRequest) (*GroupRoleDeleteResponse, error)
	// List gets a list of GroupRoles matching a given set of criteria.
	List(context.Context, *GroupRoleListRequest) (*GroupRoleListResponse, error)
	mustEmbedUnimplementedGroupsRolesServer()
}

// UnimplementedGroupsRolesServer must be embedded to have forward compatible implementations.
type UnimplementedGroupsRolesServer struct {
}

func (UnimplementedGroupsRolesServer) Create(context.Context, *GroupRoleCreateRequest) (*GroupRoleCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGroupsRolesServer) Get(context.Context, *GroupRoleGetRequest) (*GroupRoleGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGroupsRolesServer) Delete(context.Context, *GroupRoleDeleteRequest) (*GroupRoleDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGroupsRolesServer) List(context.Context, *GroupRoleListRequest) (*GroupRoleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedGroupsRolesServer) mustEmbedUnimplementedGroupsRolesServer() {}

// UnsafeGroupsRolesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupsRolesServer will
// result in compilation errors.
type UnsafeGroupsRolesServer interface {
	mustEmbedUnimplementedGroupsRolesServer()
}

func RegisterGroupsRolesServer(s grpc.ServiceRegistrar, srv GroupsRolesServer) {
	s.RegisterService(&_GroupsRoles_serviceDesc, srv)
}

func _GroupsRoles_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRoleCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsRolesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GroupsRoles/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsRolesServer).Create(ctx, req.(*GroupRoleCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupsRoles_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRoleGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsRolesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GroupsRoles/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsRolesServer).Get(ctx, req.(*GroupRoleGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupsRoles_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRoleDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsRolesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GroupsRoles/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsRolesServer).Delete(ctx, req.(*GroupRoleDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupsRoles_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRoleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsRolesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GroupsRoles/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsRolesServer).List(ctx, req.(*GroupRoleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupsRoles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.GroupsRoles",
	HandlerType: (*GroupsRolesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GroupsRoles_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GroupsRoles_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GroupsRoles_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _GroupsRoles_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "groups_roles.proto",
}
