// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GroupsHistoryClient is the client API for GroupsHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupsHistoryClient interface {
	// List gets a list of GroupHistory records matching a given set of criteria.
	List(ctx context.Context, in *GroupHistoryListRequest, opts ...grpc.CallOption) (*GroupHistoryListResponse, error)
}

type groupsHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupsHistoryClient(cc grpc.ClientConnInterface) GroupsHistoryClient {
	return &groupsHistoryClient{cc}
}

func (c *groupsHistoryClient) List(ctx context.Context, in *GroupHistoryListRequest, opts ...grpc.CallOption) (*GroupHistoryListResponse, error) {
	out := new(GroupHistoryListResponse)
	err := c.cc.Invoke(ctx, "/v1.GroupsHistory/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupsHistoryServer is the server API for GroupsHistory service.
// All implementations must embed UnimplementedGroupsHistoryServer
// for forward compatibility
type GroupsHistoryServer interface {
	// List gets a list of GroupHistory records matching a given set of criteria.
	List(context.Context, *GroupHistoryListRequest) (*GroupHistoryListResponse, error)
	mustEmbedUnimplementedGroupsHistoryServer()
}

// UnimplementedGroupsHistoryServer must be embedded to have forward compatible implementations.
type UnimplementedGroupsHistoryServer struct {
}

func (UnimplementedGroupsHistoryServer) List(context.Context, *GroupHistoryListRequest) (*GroupHistoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedGroupsHistoryServer) mustEmbedUnimplementedGroupsHistoryServer() {}

// UnsafeGroupsHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupsHistoryServer will
// result in compilation errors.
type UnsafeGroupsHistoryServer interface {
	mustEmbedUnimplementedGroupsHistoryServer()
}

func RegisterGroupsHistoryServer(s grpc.ServiceRegistrar, srv GroupsHistoryServer) {
	s.RegisterService(&_GroupsHistory_serviceDesc, srv)
}

func _GroupsHistory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupHistoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsHistoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GroupsHistory/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsHistoryServer).List(ctx, req.(*GroupHistoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupsHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.GroupsHistory",
	HandlerType: (*GroupsHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _GroupsHistory_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "groups_history.proto",
}
