// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// IdentitySetsHistoryClient is the client API for IdentitySetsHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentitySetsHistoryClient interface {
	// List gets a list of IdentitySetHistory records matching a given set of criteria.
	List(ctx context.Context, in *IdentitySetHistoryListRequest, opts ...grpc.CallOption) (*IdentitySetHistoryListResponse, error)
}

type identitySetsHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentitySetsHistoryClient(cc grpc.ClientConnInterface) IdentitySetsHistoryClient {
	return &identitySetsHistoryClient{cc}
}

func (c *identitySetsHistoryClient) List(ctx context.Context, in *IdentitySetHistoryListRequest, opts ...grpc.CallOption) (*IdentitySetHistoryListResponse, error) {
	out := new(IdentitySetHistoryListResponse)
	err := c.cc.Invoke(ctx, "/v1.IdentitySetsHistory/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentitySetsHistoryServer is the server API for IdentitySetsHistory service.
// All implementations must embed UnimplementedIdentitySetsHistoryServer
// for forward compatibility
type IdentitySetsHistoryServer interface {
	// List gets a list of IdentitySetHistory records matching a given set of criteria.
	List(context.Context, *IdentitySetHistoryListRequest) (*IdentitySetHistoryListResponse, error)
	mustEmbedUnimplementedIdentitySetsHistoryServer()
}

// UnimplementedIdentitySetsHistoryServer must be embedded to have forward compatible implementations.
type UnimplementedIdentitySetsHistoryServer struct {
}

func (UnimplementedIdentitySetsHistoryServer) List(context.Context, *IdentitySetHistoryListRequest) (*IdentitySetHistoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedIdentitySetsHistoryServer) mustEmbedUnimplementedIdentitySetsHistoryServer() {}

// UnsafeIdentitySetsHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentitySetsHistoryServer will
// result in compilation errors.
type UnsafeIdentitySetsHistoryServer interface {
	mustEmbedUnimplementedIdentitySetsHistoryServer()
}

func RegisterIdentitySetsHistoryServer(s grpc.ServiceRegistrar, srv IdentitySetsHistoryServer) {
	s.RegisterService(&_IdentitySetsHistory_serviceDesc, srv)
}

func _IdentitySetsHistory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentitySetHistoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentitySetsHistoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.IdentitySetsHistory/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentitySetsHistoryServer).List(ctx, req.(*IdentitySetHistoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentitySetsHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.IdentitySetsHistory",
	HandlerType: (*IdentitySetsHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _IdentitySetsHistory_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity_sets_history.proto",
}
