// Copyright 2020 StrongDM Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WorkflowApproversHistoryClient is the client API for WorkflowApproversHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowApproversHistoryClient interface {
	// List gets a list of WorkflowApproversHistory records matching a given set of criteria.
	List(ctx context.Context, in *WorkflowApproversHistoryListRequest, opts ...grpc.CallOption) (*WorkflowApproversHistoryListResponse, error)
}

type workflowApproversHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowApproversHistoryClient(cc grpc.ClientConnInterface) WorkflowApproversHistoryClient {
	return &workflowApproversHistoryClient{cc}
}

func (c *workflowApproversHistoryClient) List(ctx context.Context, in *WorkflowApproversHistoryListRequest, opts ...grpc.CallOption) (*WorkflowApproversHistoryListResponse, error) {
	out := new(WorkflowApproversHistoryListResponse)
	err := c.cc.Invoke(ctx, "/v1.WorkflowApproversHistory/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowApproversHistoryServer is the server API for WorkflowApproversHistory service.
// All implementations must embed UnimplementedWorkflowApproversHistoryServer
// for forward compatibility
type WorkflowApproversHistoryServer interface {
	// List gets a list of WorkflowApproversHistory records matching a given set of criteria.
	List(context.Context, *WorkflowApproversHistoryListRequest) (*WorkflowApproversHistoryListResponse, error)
	mustEmbedUnimplementedWorkflowApproversHistoryServer()
}

// UnimplementedWorkflowApproversHistoryServer must be embedded to have forward compatible implementations.
type UnimplementedWorkflowApproversHistoryServer struct {
}

func (UnimplementedWorkflowApproversHistoryServer) List(context.Context, *WorkflowApproversHistoryListRequest) (*WorkflowApproversHistoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedWorkflowApproversHistoryServer) mustEmbedUnimplementedWorkflowApproversHistoryServer() {
}

// UnsafeWorkflowApproversHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowApproversHistoryServer will
// result in compilation errors.
type UnsafeWorkflowApproversHistoryServer interface {
	mustEmbedUnimplementedWorkflowApproversHistoryServer()
}

func RegisterWorkflowApproversHistoryServer(s grpc.ServiceRegistrar, srv WorkflowApproversHistoryServer) {
	s.RegisterService(&_WorkflowApproversHistory_serviceDesc, srv)
}

func _WorkflowApproversHistory_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowApproversHistoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowApproversHistoryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.WorkflowApproversHistory/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowApproversHistoryServer).List(ctx, req.(*WorkflowApproversHistoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkflowApproversHistory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.WorkflowApproversHistory",
	HandlerType: (*WorkflowApproversHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _WorkflowApproversHistory_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow_approvers_history.proto",
}
